name: responsive_dash_board
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.5.3
dependencies:
  cupertino_icons: ^1.0.8
  device_preview: ^1.2.0
  expandable_page_view: ^1.0.17
  fl_chart: ^0.69.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
flutter_assets:
  assets_path: assets/images
  output_path: lib/utils
  filename: app_images.dart
  field_prefix: null
